---
title: "Sample codes for reading and analyzing growth data"
author: Rishav Ray
output: 
 - html_document
 - md_document
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

Using the code from Dexuan here with modifications.
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(lubridate)
library(janitor)
library(purrr)
library(readr)
library(ggthemes)
#setwd("C:/Users/Tobyz/Desktop/S.tort-light-growth/Data")
```
*import plant data*
```{r}
#import
files <- list.files(path = "Data/", pattern = "WL2_size_survey_.*_corrected\\.csv", full.names = TRUE)

safe_read_process <- safely(function(f) {
  df <- read_csv(f, col_types = cols(.default = "c")) %>%
    clean_names()
  df$source_file <- f
  return(df)
})

results <- map(files, safe_read_process)
successful_results <- keep(results, ~ !is.null(.x$result))
successful_data <- bind_rows(map(successful_results, "result"), .id = "source_index")

#clean data
plant <- successful_data %>%
  select(-starts_with("x"))%>%
  mutate(
    height_cm = parse_number(height_cm),
    long_leaf_cm = parse_number(long_leaf_cm),
    date=mdy(date)
  )
```

```{r}
summary(plant)
```

*consolidate light measurement to a weekly measurement*
```{r}
#import light data
light_raw <- read_csv("Data/IntBioHalfHourTable_clean.txt")

#weekly measurement
weekly_light <- light_raw %>%
  mutate(
    timestamp = ymd_hms(TIMESTAMP),
    SlrW_Avg = as.numeric(SlrW_Avg),  # turn into number format
    week = floor_date(timestamp, "week")
  ) %>%
  group_by(week) %>%
  summarise(
    weekly_avg_SlrW = mean(SlrW_Avg, na.rm = TRUE),
    .groups = "drop"
  )

# result
print(weekly_light)
```

*compute growth from size measurements*
```{r}
plant_growth <- plant %>%
  filter(date %in% as.Date(c("2023-08-02", "2023-10-23"))) %>%
  group_by(block, bed, bed_row, bed_col) %>%
  arrange(date) %>%
  summarise(
    height_growth = diff(height_cm),
    leaf_growth = diff(long_leaf_cm),
    .groups = "drop"
  )
```

Plot a growth curve
```{r}
'''
plat_growth = plant |>
unite("PID", pop:rep, sep = "_") |> # create a unique plant ID
mutate(date_axis = format(date, "%b %e"),
date_axis = factor(date_axis, levels = unique(date_axis))) |>
select(PID, date_axis, height_cm)
'''
# Will write this data once in a csv and read it in next time
# write_csv(plat_growth, "Data/plant_growth.csv")
plant_growth = read_csv("Data/plant_growth.csv")


ggplot(plat_growth, aes(x = date_axis, y = height_cm, group = PID)) +
  geom_line() +
  labs(title = "Growth Curve of Plants", x = "Date", y = "Height (cm)") +
  theme_bw() +
  theme(legend.position = "bottom")
```

There is a strange gap in October 13 and September 27. Need to investigate.






