---
title: "S.tort-light-growth"
output: html_document
date: "2025-06-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(lubridate)
library(janitor)
library(purrr)
library(readr)
setwd("C:/Users/Tobyz/Desktop/S.tort-light-growth/Data")
```
*import plant data*
```{r}
#import
files <- list.files(pattern = "WL2_size_survey.*\\.csv$")

safe_read_process <- safely(function(f) {
  df <- read_csv(f, col_types = cols(.default = "c")) %>%
    clean_names()
  df$source_file <- f
  return(df)
})

results <- map(files, safe_read_process)
successful_results <- keep(results, ~ !is.null(.x$result))
successful_data <- bind_rows(map(successful_results, "result"), .id = "source_index")

#clean data
plant <- successful_data %>%
  select(-starts_with("x"))%>%
  mutate(
    height_cm = parse_number(height_cm),
    long_leaf_cm = parse_number(long_leaf_cm),
    date=mdy(date)
  )
```

```{r}
summary(plant)
```

*consolidate light measurement to a weekly measurement*
```{r}
#import light data
light_raw <- read_csv("CR1000XSeries_IntBioHalfHourTable.txt", skip = 1, show_col_types = FALSE)

#weekly measurement
weekly_light <- light_raw %>%
  mutate(
    timestamp = ymd_hms(TIMESTAMP),
    SlrW_Avg = as.numeric(SlrW_Avg),  # turn into number format
    week = floor_date(timestamp, "week")
  ) %>%
  group_by(week) %>%
  summarise(
    weekly_avg_SlrW = mean(SlrW_Avg, na.rm = TRUE),
    .groups = "drop"
  )

# result
print(weekly_light)
```

*compute growth from size measurements*
```{r}
plant_growth <- plant %>%
  filter(date %in% as.Date(c("2023-08-02", "2023-10-23"))) %>%
  group_by(block, bed, bed_row, bed_col) %>%
  arrange(date) %>%
  summarise(
    height_growth = diff(height_cm),
    leaf_growth = diff(long_leaf_cm),
    .groups = "drop"
  )
```









